In [7]:
import pandas as pd

athlete_events = pd.read_csv('athlete_events.csv')
noc_regions = pd.read_csv('noc_regions.csv')

In [8]:
athlete_events.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [9]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [6]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [10]:
athlete_events.shape

(271116, 15)

In [11]:
noc_regions.shape

(230, 3)

In [12]:
athlete_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [13]:
noc_regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     230 non-null    object
 1   region  227 non-null    object
 2   notes   21 non-null     object
dtypes: object(3)
memory usage: 5.5+ KB

In [14]:
athlete_events.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [15]:
noc_regions.isnull().sum()

NOC         0
region      3
notes     209
dtype: int64

In [16]:
athlete_events_clean = athlete_events.copy()
noc_regions_clean = noc_regions.copy()

athlete_events_clean["Medal"] = athlete_events_clean["Medal"].fillna("No Medal")
noc_regions_clean["region"] = noc_regions_clean["region"].fillna("Unknown")
noc_regions_clean["notes"] = noc_regions_clean["notes"].fillna("")

In [17]:
athlete_events_clean.isnull().sum()

ID            0
Name          0
Sex           0
Age        9474
Height    60171
Weight    62875
Team          0
NOC           0
Games         0
Year          0
Season        0
City          0
Sport         0
Event         0
Medal         0
dtype: int64

In [19]:
noc_regions_clean.isnull().sum()

NOC       0
region    0
notes     0
dtype: int64

In [20]:
import sqlite3

conn = sqlite3.connect("olympics_capstone.db")

athlete_events_clean.to_sql("athlete_events", conn, if_exists="replace", index=False)
noc_regions_clean.to_sql("noc_regions", conn, if_exists="replace", index=False)

In [21]:
query = """
SELECT *
FROM athlete_events
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No Medal
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,No Medal
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,No Medal
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",No Medal
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,No Medal
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",No Medal
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,No Medal
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",No Medal

In [22]:
query = """
SELECT 
    ae.Name,
    ae.Sex,
    ae.Age,
    ae.Team,
    ae.NOC,
    nr.region,
    ae.Year,
    ae.Season,
    ae.Sport,
    ae.Event,
    ae.Medal
FROM athlete_events ae
LEFT JOIN noc_regions nr
    ON ae.NOC = nr.NOC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,Name,Sex,Age,Team,NOC,region,Year,Season,Sport,Event,Medal
0,A Dijiang,M,24.0,China,CHN,China,1992,Summer,Basketball,Basketball Men's Basketball,No Medal
1,A Lamusi,M,23.0,China,CHN,China,2012,Summer,Judo,Judo Men's Extra-Lightweight,No Medal
2,Gunnar Nielsen Aaby,M,24.0,Denmark,DEN,Denmark,1920,Summer,Football,Football Men's Football,No Medal
3,Edgar Lindenau Aabye,M,34.0,Denmark/Sweden,DEN,Denmark,1900,Summer,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,Christine Jacoba Aaftink,F,21.0,Netherlands,NED,Netherlands,1988,Winter,Speed Skating,Speed Skating Women's 500 metres,No Medal
5,Christine Jacoba Aaftink,F,21.0,Netherlands,NED,Netherlands,1988,Winter,Speed Skating,"Speed Skating Women's 1,000 metres",No Medal
6,Christine Jacoba Aaftink,F,25.0,Netherlands,NED,Netherlands,1992,Winter,Speed Skating,Speed Skating Women's 500 metres,No Medal
7,Christine Jacoba Aaftink,F,25.0,Netherlands,NED,Netherlands,1992,Winter,Speed Skating,"Speed Skating Women's 1,000 metres",No Medal
8,Christine Jacoba Aaftink,F,27.0,Netherlands,NED,Netherlands,1994,Winter,Speed Skating,Speed Skating Women's 500 metres,No Medal
9,Christine Jacoba Aaftink,F,27.0,Netherlands,NED,Netherlands,1994,Winter,Speed Skating,"Speed Skating Women's 1,000 metres",No Medal

In [23]:
query = """
SELECT 'athlete_events' AS table_name, COUNT(*) AS row_count
FROM athlete_events

UNION ALL

SELECT 'noc_regions' AS table_name, COUNT(*) AS row_count
FROM noc_regions;
"""

pd.read_sql_query(query, conn)

       table_name  row_count
0  athlete_events     271116
1     noc_regions        230

In [24]:
query = """
SELECT 
    MIN(Year) AS first_year,
    MAX(Year) AS last_year,
    COUNT(DISTINCT Year) AS number_of_years
FROM athlete_events;
"""

pd.read_sql_query(query, conn)

   first_year  last_year  number_of_years
0        1896       2016               35

In [25]:
query = """
SELECT 
    COUNT(DISTINCT ID) AS unique_athletes,
    COUNT(DISTINCT Sport) AS unique_sports,
    COUNT(DISTINCT Event) AS unique_events,
    COUNT(DISTINCT NOC) AS unique_nocs,
    COUNT(DISTINCT Games) AS unique_games
FROM athlete_events;
"""

pd.read_sql_query(query, conn)

   unique_athletes  unique_sports  unique_events  unique_nocs  unique_games
0           135571             66            765          230            51

In [26]:
query = """
SELECT 
    Medal,
    COUNT(*) AS count
FROM athlete_events
GROUP BY Medal
ORDER BY count DESC;
"""

pd.read_sql_query(query, conn)

      Medal   count
0  No Medal  231333
1      Gold   13372
2    Bronze   13295
3    Silver   13116

In [27]:
query = """
SELECT 
    Year,
    Sex,
    COUNT(DISTINCT ID) AS athlete_count
FROM athlete_events
GROUP BY Year, Sex
ORDER BY Year, Sex;
"""

pd.read_sql_query(query, conn)

    Year Sex  athlete_count
0   1896   M            176
1   1900   F             23
2   1900   M           1201
3   1904   F              6
4   1904   M            644
..   ...  ..            ...
64  2012   M           5863
65  2014   F           1102
66  2014   M           1643
67  2016   F           5034
68  2016   M           6145

[69 rows x 3 columns]

In [28]:
query = """
SELECT 
    nr.region,
    COUNT(*) AS total_medals
FROM athlete_events ae
LEFT JOIN noc_regions nr
    ON ae.NOC = nr.NOC
WHERE ae.Medal != 'No Medal'
GROUP BY nr.region
ORDER BY total_medals DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

      region  total_medals
0        USA          5637
1     Russia          3947
2    Germany          3756
3         UK          2068
4     France          1777
5      Italy          1637
6     Sweden          1536
7     Canada          1352
8  Australia          1349
9    Hungary          1135